data:
  # 데이터 경로
  train_csv: "/data/ephemeral/pro-nlp-generationfornlp-nlp-13/data/train.csv"
  test_csv: "/data/ephemeral/pro-nlp-generationfornlp-nlp-13/data/test.csv"
  
  # 전처리
  max_token_length: 2048
  test_size: 0.1
  
  # 데이터 증강
  augmentation:
  
  # ICL 설정
  icl:

