data:
  # 데이터 경로
  train_csv: "/data/ephemeral/pro-nlp-generationfornlp-nlp-13/data/train.csv"
  test_csv: "/data/ephemeral/pro-nlp-generationfornlp-nlp-13/data/test.csv"
  
  # 전처리
  max_token_length: 1024
  test_size: 0.1
  
  # 토크나이저
  tokenizer:
    model_name: "beomi/gemma-ko-2b"
    padding_side: "right"
    num_proc: 4
  
  # 데이터 증강
  augmentation:
  
  # ICL 설정
  icl:

